dist: xenial
language: node_js
node_js:
  - 14
before_install:
  - npm install -g qunit-puppeteer
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 test/test.html &
  - qunit-puppeteer test/test.html